### ISSUE TITLE
Adding more switches instead of DAT editing - or even allow for "override config"

### ISSUE THREAD

**Issue by zeffy** [Evengard/bnsnogg#2]
I seriously appreciate the work you've done on this, I wouldn't even be playing BnS at this point if I had to let GG run on my machine.

:+1:

Edit: I guess I did have a question, when you use the `/configdatoverride` option, does the config2.dat file need to have *all* of the settings as the original, or just specific options you want changed?

**Comment by Evengard** [comment]
Thanks! Got so much hate on reddit, so this is kind of a relief for me :)

About the config.dat. You need to have all of the settings. It's a complete override - it just loads config2.dat instead of config.dat. Is there something specific you want to change in it?

**Comment by zeffy** [comment]
Yeah man, I saw your post on reddit and was kind of horrified by the replies. I'd been using your original bypass for months with no issues, so I couldn't understand the backlash tbh. :roll_eyes: 

And oh okay, yeah that makes sense!

As for your question, these are the changes I usually make: 

`xml.dat/client.config2.xml` 
- set all options under `damage-meter` to `y`

`config.dat/system.config2.xml`
- blank out `executionlog-url` 
- set `show-clause` to `false`
- set `limit-time-for-user-away-status` to `0`

If you were interested in adding any of those as switches in bnsnogg, that would be really awesome. But it's not a huge deal for me to recompile the .dats after updates, so no pressure of course. :)

Thanks again for all your effort!

**Comment by Evengard** [comment]
I'll think abut it, but it will be on low priority. Thanks for the advice though, seems logical to patch theese out too. I'll keep it open.

**Comment by zeffy** [comment]
It seems there was an update to the BnS backend today that "fixed" the workaround for noweblaunching, which forces everyone to use the official launcher. 

This makes your /configdatoverride option unusable (as well as any modifications to xml.dat), because Client.exe can't be started directly, and it the official launcher repairs the files before running the game.

I don't know if you are still interested in tackling the things we discussed before, but seems like it could be a potential fix for at least some of the problems introduced by this backend update. 

Another option could be using some other means to tell bnsnogg to load the secondary .dat files (maybe simply checking for the existence of a config2.dat?) But that still leaves the problem of not being able to modify xml.dat.

Just thought I would bring this to your attention. Thanks again for your excellent work!

**Comment by zeffy** [comment]
Hey, just following up on my last comment. I used the source code for another project called [BNSBoost](https://github.com/Xyene/BNSBoost), and wrote a fake steam_api.dll that you can use to bypass the file integrity checks in NC Launcher, so you can load the game with modified .upks, xml.dat, config.dat, etc (any file used by the game).

My project is located here https://github.com/zeffy/bnsboost-steam_api.dll and IMHO it complements bnsnogg very well.

You can probably close this issue if you want, since the features I was requesting are no longer really necessary.
